version: '3'

services:
  database:
    image: 'postgres:latest'
    ports:
      - 5434:5432

    environment:
      POSTGRES_USER: postgres # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: postgres # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: rock # The PostgreSQL default database (automatically created at first launch)

  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - database